[project]
name = "pycms"
version = "0.1.0"
description = "A stunning headless CMS for Python"
authors = ["misostack", "pybase.net"]
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "django>=5.1.6",
    "django-filter>=25.1",
    "djangorestframework>=3.15.2",
]
